Repository adierkens/webpack-inject-plugin, pull requests merged in 2019-04, with the labels that each got.

#23 Add support for a function as an entryName
  README.md
  jest.config.js
  src/__tests__/main.test.ts
  src/main.ts
Labels: minor

#24 Update jest
  jest.config.js
  package-lock.json
  package.json
Labels: skip-release

#25 Update README.md
  README.md
Labels: skip-release

#26 fix(doc): rename entry order option name
  README.md
Labels: documentation, skip-release

#27 feat(plugin): Change how ID are handled for the injected loader
  src/main.ts
Labels: minor

#28 Add loaderID to README
  README.md
Labels: documentation, skip-release
